CREATE TABLE IF NOT EXISTS `yy_im_callback_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_key` CHAR(64) NOT NULL,
  `trace_id` VARCHAR(64) NOT NULL,
  `callback_command` VARCHAR(128) NOT NULL,
  `sdk_app_id` VARCHAR(32) NOT NULL,
  `event_time` VARCHAR(32) NOT NULL DEFAULT '',
  `from_account` VARCHAR(255) NOT NULL DEFAULT '',
  `to_account` VARCHAR(255) NOT NULL DEFAULT '',
  `group_id` VARCHAR(255) NOT NULL DEFAULT '',
  `msg_seq` VARCHAR(32) NOT NULL DEFAULT '',
  `msg_random` VARCHAR(32) NOT NULL DEFAULT '',
  `payload_json` LONGTEXT NOT NULL,
  `handler_status` VARCHAR(20) NOT NULL DEFAULT 'received',
  `error_message` VARCHAR(1000) NOT NULL DEFAULT '',
  `duplicate_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `received_at` INT UNSIGNED NOT NULL,
  `last_received_at` INT UNSIGNED NOT NULL,
  `processed_at` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_key` (`event_key`),
  KEY `idx_command_received` (`callback_command`, `received_at`),
  KEY `idx_status_received` (`handler_status`, `received_at`),
  KEY `idx_from_account` (`from_account`),
  KEY `idx_group_id` (`group_id`),
  KEY `idx_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
