<?php

return [
    'type' => 'mysql',
    'hostname' => getenv('DB_HOST') ?: 'mysql',
    'database' => getenv('DB_NAME') ?: 'jishitongxun_com',
    'username' => getenv('DB_USER') ?: 'jishitongxun_com',
    'password' => getenv('DB_PASSWORD') ?: '',
    'hostport' => getenv('DB_PORT') ?: '3306',
    'dsn' => '',
    'params' => [],
    'charset' => 'utf8mb4',
    'prefix' => getenv('DB_PREFIX') ?: 'yy_',
    'debug' => false,
    'deploy' => 0,
    'rw_separate' => false,
    'master_num' => 1,
    'slave_no' => '',
    'read_master' => false,
    'fields_strict' => true,
    'resultset_type' => 'array',
    'auto_timestamp' => false,
    'datetime_format' => 'Y-m-d H:i:s',
    'sql_explain' => false,
    'builder' => '',
    'query' => '\\think\\db\\Query',
    'break_reconnect' => true,
    'break_match_str' => [],
];
